  new file:   html5up-strata/LICENSE.txt
        new file:   html5up-strata/README.txt
        new file:   html5up-strata/assets/css/fontawesome-all.min.css
        new file:   html5up-strata/assets/css/images/overlay.png
        new file:   html5up-strata/assets/css/main.css
        new file:   html5up-strata/assets/js/breakpoints.min.js
        new file:   html5up-strata/assets/js/browser.min.js
        new file:   html5up-strata/assets/js/jquery.min.js
        new file:   html5up-strata/assets/js/jquery.poptrox.min.js
        new file:   html5up-strata/assets/js/main.js
        new file:   html5up-strata/assets/js/util.js
        new file:   html5up-strata/assets/sass/libs/_breakpoints.scss
        new file:   html5up-strata/assets/sass/libs/_functions.scss
        new file:   html5up-strata/assets/sass/libs/_html-grid.scss
        new file:   html5up-strata/assets/sass/libs/_mixins.scss
        new file:   html5up-strata/assets/sass/libs/_vars.scss
        new file:   html5up-strata/assets/sass/libs/_vendor.scss
        new file:   html5up-strata/assets/sass/main.scss
        new file:   html5up-strata/assets/webfonts/fa-brands-400.eot
        new file:   html5up-strata/assets/webfonts/fa-brands-400.svg
        new file:   html5up-strata/assets/webfonts/fa-brands-400.ttf
        new file:   html5up-strata/assets/webfonts/fa-brands-400.woff
        new file:   html5up-strata/assets/webfonts/fa-brands-400.woff2
        new file:   html5up-strata/assets/webfonts/fa-regular-400.eot
        new file:   html5up-strata/assets/webfonts/fa-regular-400.svg
        new file:   html5up-strata/assets/webfonts/fa-regular-400.ttf
        new file:   html5up-strata/assets/webfonts/fa-regular-400.woff
        new file:   html5up-strata/assets/webfonts/fa-regular-400.woff2
        new file:   html5up-strata/assets/webfonts/fa-solid-900.eot
        new file:   html5up-strata/assets/webfonts/fa-solid-900.svg
        new file:   html5up-strata/assets/webfonts/fa-solid-900.ttf
        new file:   html5up-strata/assets/webfonts/fa-solid-900.woff
        new file:   html5up-strata/assets/webfonts/fa-solid-900.woff2
        new file:   html5up-strata/images/avatar.jpg
        new file:   html5up-strata/images/avatar.svg
        new file:   html5up-strata/images/bg.jpg
        new file:   html5up-strata/images/fulls/01.jpg
        new file:   html5up-strata/images/fulls/02.jpg
        new file:   html5up-strata/images/fulls/02.png
        new file:   html5up-strata/images/fulls/03.jpg
        new file:   html5up-strata/images/fulls/04.jpg
        new file:   html5up-strata/images/fulls/05.jpg
        new file:   html5up-strata/images/fulls/06.jpg
        new file:   html5up-strata/images/fulls/3.jpg
        new file:   html5up-strata/images/fulls/4.jpg
        new file:   html5up-strata/images/fulls/5.jpg
        new file:   html5up-strata/images/fulls/6.png
        new file:   html5up-strata/images/fulls/responsive_2.png
        new file:   html5up-strata/images/thumbs/01.jpg
        new file:   html5up-strata/images/thumbs/02.jpg
        new file:   html5up-strata/images/thumbs/03.jpg
        new file:   html5up-strata/images/thumbs/04.jpg
        new file:   html5up-strata/images/thumbs/05.jpg
        new file:   html5up-strata/images/thumbs/06.jpg
        new file:   html5up-strata/index.html
        new file:   index.html
        new file:   package-lock.json
        new file:   package.json